language: ruby
rvm:
  - 2.0.0

env:
  - DB=postgresql
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libtag1-dev
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres