language: ruby
rvm:
  - 2.0.0
env:
  - DB=mysql
before_install:
  - sudo apt-get update -qq
install:
  - "bundle install --deployment --without production"
branches:
  only:
    - 'master'
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - mysql -e 'create database myapp_test'
  - "sudo apt-get install -y libtag1-dev"