#From Github
development:
  adapter: postgresql
  database: mp3_ci_dev
  username: postgres
  password: root

test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres

production:
  adapter: postgresql
  database: travis_ci_test
  username: postgres
